<?php
return [
    'data' => [
        'dest_country_id' => 'BR',
        'dest_region_id' => '82',
        'dest_region_code' => 'SP',
        'dest_street' => 'Turmstraße 17',
        'dest_city' => 'Berlin',
        'dest_postcode' => '82810160',
        'dest_postal' => '10559',
        'package_value' => '5',
        'package_value_with_discount' => '5',
        'package_weight' => '5',
        'package_qty' => '1',
        'package_physical_value' => '5',
        'free_method_weight' => '5',
        'store_id' => '1',
        'website_id' => '1',
        'free_shipping' => '0',
        'limit_carrier' => null,
        'base_subtotal_incl_tax' => '5',
        'orig_country_id' => 'BR',
        'country_id' => 'BR',
        'region_id' => '12',
        'city' => 'Fremont',
        'orig_postcode' => '89300000',
        'girth' => null,
        'height' => null,
        'length' => null,
        'width' => null,
        'weight' => 1,
        'limit_method' => 'IE',
        'all_items' => [],
    ]
];
