<?php
namespace Weverson83\Correios\Model\Source;
use Magento\Framework\Option\ArrayInterface;
use Weverson83\Correios\Model\Method\Method;

/**
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @author    Weverson Cachinsky <weversoncachinsky@gmail.com>
 */
class MethodList implements ArrayInterface
{
    /**
     * @var \Magento\Framework\Config\Data
     */
    private $methodList;

    public function __construct(\Magento\Framework\Config\Data $methodList)
    {
        $this->methodList = $methodList;
    }

    /**
     * Return array of options as value-label pairs
     *
     * @return array Format: array(array('value' => '<value>', 'label' => '<label>'), ...)
     */
    public function toOptionArray()
    {
        /** @var Method[] $methods */
        $methods = $this->methodList->get('methods');
        $outputArray = [];

        foreach ($methods as $method) {
            $outputArray[] = [
                'value' => $method->getCode(),
                'label' => $method->getLabel(),
            ];
        }

        return $outputArray;
    }

    public function toArray()
    {
        return array_reduce($this->toOptionArray(), function (array $result, $option) {
            $result[] = $option['value'];

            return $result;
        }, []);
    }
}
