<?php
namespace Weverson83\Correios\Model\Config;

/**
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @author    Weverson Cachinsky <weversoncachinsky@gmail.com>
 */
class Path
{
    const USERNAME = 'carriers/correios/username';
    const PASSWORD = 'carriers/correios/password';
    const ALLOWED_METHODS = 'carriers/correios/allowed_methods';
    const USE_DECLARED_VALUE = 'carriers/correios/declared_value';
    const NOTIFY_DELIVERY = 'carriers/correios/notify_delivery';
    const GATEWAY_URL = 'carriers/correios/gateway_url';
    const PACKAGE_TYPE = 'carriers/correios/package_type';
    const SHOW_ESTIMATE = 'carriers/correios/show_estimate';
    const ADD_DAYS_TO_ESTIMATE = 'carriers/correios/add_days_to_estimate';
}
